# Generated by Django 3.2.5 on 2021-08-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallbackToken',
        ),
        migrations.DeleteModel(
            name='PasswordlessAccount',
        ),
    ]
